CREATE TABLE [dbo].[BENEFICIARIOS] (
    [ID]         BIGINT       IDENTITY (1, 1) NOT NULL,
    [CPF]        VARCHAR (11) NOT NULL,
    [NOME]       VARCHAR (50) NOT NULL,
    [IDCLIENTE]  BIGINT       NOT NULL,
    [DTEXCLUSAO] DATETIME     NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

